### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wezpyke** [ijse/gulp-freemarker#6]
I'm using a Windows machine at the moment and I'm getting the following error

> Error: ENOENT: no such file or directory, open 'C:\Users\wez\AppData\Local\T
> emp\30419676-678e-47a9-b92f-9cd1821fc3df'
>     at Error (native)

I'm using code that is almost identical to the code you have supplied in your readme.

> gulp.task('default', function () {
>   return gulp.src("./mock/*.json")
>   .pipe(freemarker({
>       viewRoot: "WEB-INF/views/",
>       options: {}
>   }))
>   .pipe(gulp.dest("./www"));
> });

My directory structure is as follows:
my-project/
gulpfile.js
package.json
mock/
-/hello.json
WEB-INF/
-/views/
--/hello.ftl

**Comment by lxlneo** [comment]
try change the viewRoot  to absolute path

```
gulp.task('default', function () {
return gulp.src("./mock/*.json")
.pipe(freemarker({
viewRoot: __dirname+"/WEB-INF/views",
options: {}
}))
.pipe(gulp.dest("./www"));
});
```

**Comment by wezpyke** [comment]
@lxlneo this fixed the issue for me.
